#!/bin/bash
#
# Dependencies
# LESS (set by ~/.bash/applications/less)
# LS_CMD (set by ~/.bash/variables)

alias ll='ls_with_arg -l' # probably don't need the extra L but I'm used to it.
alias la='ls_with_arg -la'
alias lhl='ls_with_arg -hl'
# Trailing space is load-bearing!
alias s='sudo '

ls_with_arg() {
  # $1 ls args
  # $2 target or empty
  #
  # Mimicking:
  # $ ls <args> <target> | less
  #
  if [ -z "$2" ]; then
    $LS_CMD $1 | less
  else
    $LS_CMD $1 "$2" | less
  fi
}

hex_string() {
  # $1 length
  cat /dev/urandom | env LC_CTYPE=C tr -cd 'a-f0-9' | head -c "$1"
}
