#!/bin/bash
#
# A replacement for traditional .bashrc/.bash_profile initialization.
#
# .bash_history options
export HISTFILESIZE=2000
#  don't put duplicate lines in the history. See bash(1) for more options
#  don't overwrite GNU Midnight Commander's setting of `ignorespace'.
export HISTCONTROL=$HISTCONTROL${HISTCONTROL+,}ignoredups
#  ... or force ignoredups and ignorespace
export HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

umask 002

# If not running interactively, don't do anything else.
[ -z "$PS1" ] && return
# I've also seen checks for interactive mode of the form:
#
# $ [[ ! ($- =~ "i") ]] && return
# The former is more compact.

# #Interactive-only configuration

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# Case insensitive filenames for globbing
shopt -s nocaseglob

# Case insensitive filenames for tab completion
bind 'set completion-ignore-case on'

# I'll need this if it doesn't already exist.
custom_dirs=(
    "bin"
    "Workspace"
)
for name in ${custom_dirs[@]}; do
    [ ! -d "$HOME/$name" ] && mkdir "$HOME/$name"
done

# Complicated initialization, extracted to separate modules for readability.
# Order matters.
init_files=(
    "path"
    "variables"
    "aliases"
    "prompt"
)
for file in ${init_files[@]}; do
  if [ -f ~/.bash/$file ]; then
    . ~/.bash/$file
  else
    >&2 echo "~/.bash/$file does not exist, your shell is improperly configured!"
  fi
done

# Applications
for app in ~/.bash/applications/*; do
  . $app
done
