#!/bin/bash
#
paths=(
    "$HOME/bin"
    "/usr/local/bin"
    "$HOME/.composer/vendor/bin"
    "$HOME/.rvm/bin"
    "/usr/local/sbin"
    "/usr/bin"
    "/usr/sbin"
    "/bin"
    "/sbin"
	"$HOME/Workspace/hotpads/devops/bin"
)

export PATH=""
for path in ${paths[@]}; do
  [ -d "$path" ] && PATH="$PATH":"$path"
done
PATH=${PATH:1:${#PATH}}  # In case you forget, this trims the leading ":"

export PATH


