#!/bin/bash
#
# Setup global variables that I use or use downstream
export EDITOR=vim

[ -d "$HOME/Library/Android/sdk" ] && export ANDROID_HOME="$HOME/Library/Android/sdk"

if [ -d "/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home" ]; then
	export JAVA_HOME="/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home"
else
	>&2 echo "JAVA_HOME of \"/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home\" does not exist. Atlassian SDK commands will not work." 
fi

if [ -d "$HOME/Workspace/repos" ]; then
    export REPOS="$HOME/Workspace/repos"
    export GUARD_DIR="$REPOS"
fi
LS_CMD_set () {
    # Ensures that our `ls` command is the one that can group directories. If it's not available, an error message is
    # printed. End result is that LS_CMD is set.
    #
    local path=$(type -P gls)
    if [ $? ]; then
        export LS_CMD="$path -G --group-directories-first --color=always"
        return
    fi
    >&2 echo "gls missing; no directory grouping is possible."
    export LS_CMD="/bin/ls -G --color=always"
}
LS_CMD_set

# Useful for creating the remote on new systems.
export DOTFILES_REMOTE="https://github.com/phasetwenty/dotfiles.git"
