#!/bin/bash
#
# Setup global variables that I use or use downstream
export EDITOR=vim

if [ -d "$HOME/Workspace/repos" ]; then
    export REPOS="$HOME/Workspace/repos"
    export GUARD_DIR="$REPOS"
fi

export LS_CMD="$(type -P ls) -G --group-directories-first --color=always"

# Useful for creating the remote on new systems.
export DOTFILES_REMOTE="https://github.com/phasetwenty/dotfiles.git"