#!/bin/bash
#
# This file must be sourced (and not executed standalone).
# TODO: find out how to safely return whether the script was sourced or executed in a subshell

composer () {
	php -d memory_limit=-1 "$path_to_composer" "$@"
}

init_composer () {
	export path_to_composer=$(type -P composer)
	# If composer isn't available on this system return
	[ -z "$path_to_composer" ] && unset -f composer
		
	
}
init_composer

