#!/bin/bash
#
# This file must be sourced (and not executed standalone).
# TODO: find out how to safely return whether the script was sourced or executed in a subshell

# If git isn't available on this system return
[ ! $(type -P git) ] && return

# Completion, has no dependencies
if [ ! -f ~/.gitrc/git-completion ]; then
  >&2 echo "git-completion is not available!"
else
    # This script is hundreds of lines long, and I felt it would be easier to keep it contained.
  . ~/.gitrc/git-completion
fi

alias cleano='find . -name "*.orig" -exec rm {} \;'


# Creates branches with less typing.
topic-base() {
  # $1 Branch name (e.g., FENNEL, FOX, GRAVY, GOAT)
  # $2 Release #
  # $3 Ticket number (assumes ISLM ticket)
  if [ -z "$2" ] || [ -z "$3" ]; then
    return
  fi

  prefix=$(echo "$1" | cut -c 1-1 | tr '[:lower:]' '[:upper:]')
  git checkout -b $prefix$2-ISLM-$3 -t origin/$1$2
}
