#!/bin/bash
#
# This file must be sourced (and not executed standalone).
# TODO: find out how to safely return whether the script was sourced or executed in a subshell
#
# This does both the rvm setup and guard, since we setup guard in our rvm environment.
#
goguard () {
  cd "$GUARD_DIR"
  bundle exec guard
  cd "$OLDPWD"
}

setup_rvm () {
    local ruby_version_string="ruby-2.3.0"

    if [ ! -x ~/.rvm/scripts/rvm ]; then
        >&2 echo "rvm not available, cannot setup guard."
        return 1
    fi

    . "$HOME/.rvm/scripts/rvm"
    rvm use $ruby_version_string &>/dev/null
    return 0
}
setup_rvm
