#!/bin/bash
#
nvm_init () {
	local path_to_nvm_sh="/usr/local/opt/nvm/nvm.sh"
    local path_to_nvm_home="$HOME/.nvm"

	if [ ! -f "$path_to_nvm_sh" ]; then
		>&2 echo "NVM does not exist on this system, no NVM commands will be available."
		return
	fi

	[ -d "$path_to_nvm_home" ] || mkdir "$path_to_nvm_home"
    export NVM_DIR="$path_to_nvm_home"
	. "$path_to_nvm_sh"

	nvm use stable >/dev/null
}
nvm_init
